"""
Gold Layer - Dimension Country Configuration

Source: derived from `silver.hotels_reviews` (column `reviewer_country`)
Target: gold.dim_country (Iceberg table)
"""

# Source table in Silver catalog
SOURCE_TABLE = "hotels_reviews"
SOURCE_COLUMN = "reviewer_country"

# Source catalog/database for Silver. Use fully-qualified name when referencing tables
SOURCE_CATALOG = "silver"
SOURCE_DATABASE = "silver"

# Target table (catalog.database.table)
GOLD_CATALOG = "gold"
GOLD_DATABASE = "gold"
GOLD_TABLE = "dim_country"
GOLD_TABLE_FULL = f"{GOLD_CATALOG}.{GOLD_DATABASE}.{GOLD_TABLE}"

# Business key: country name
BUSINESS_KEY = ["country_name"]

# Optional: manual mapping from country_name -> region (e.g., 'Vietnam': 'Asia')
# Leave empty or add as needed.
COUNTRY_TO_REGION = {
    "Việt Nam": "Asia",
    "Úc": "Oceania",
    "Pháp": "Europe",
    "Vương Quốc Anh": "Europe",
    "Đức": "Europe",
    "Mỹ": "North America",
    "Tây Ban Nha": "Europe",
    "Hà Lan": "Europe",
    "Ý": "Europe",
    "Trung Quốc": "Asia",
    "Nga": "Europe",
    "Nhật Bản": "Asia",
    "Ấn Độ": "Asia",
    "Hàn Quốc": "Asia",
    "Canada": "North America",
    "Thụy Sỹ": "Europe",
    "Singapore": "Asia",
    "Bỉ": "Europe",
    "New Zealand": "Oceania",
    "Ba Lan": "Europe",
    "Malaysia": "Asia",
    "Israel": "Asia",
    "Thái Lan": "Asia",
    "Ireland": "Europe",
    "Cộng hoà Séc": "Europe",
    "Đan Mạch": "Europe",
    "Áo": "Europe",
    "nan": "Unknown",
    "Thụy Điển": "Europe",
    "Philippines": "Asia",
    "Na Uy": "Europe",
    "Bồ Đào Nha": "Europe",
    "United Arab Emirates": "Asia",
    "Phần Lan": "Europe",
    "Hungary": "Europe",
    "Brazil": "South America",
    "Nam Phi": "Africa",
    "Kazakhstan": "Asia",
    "Saudi Arabia": "Asia",
    "Indonesia": "Asia",
    "Hy Lạp": "Europe",
    "Romania": "Europe",
    "Argentina": "South America",
    "Thổ Nhĩ Kỳ": "Asia/Europe",
    "Chile": "South America",
    "Slovakia": "Europe",
    "Lithuania": "Europe",
    "Slovenia": "Europe",
    "Campuchia": "Asia",
    "Belarus": "Europe",
    "Ukraine": "Europe",
    "Mexico": "North America",
    "Estonia": "Europe",
    "Colombia": "South America",
    "Mông Cổ": "Asia",
    "Bulgaria": "Europe",
    "Croatia": "Europe",
    "Reunion": "Africa",
    "Qatar": "Asia",
    "Latvia": "Europe",
    "Luxembourg": "Europe",
    "Bangladesh": "Asia",
    "Sri Lanka": "Asia",
    "Serbia": "Europe",
    "Oman": "Asia",
    "Morocco": "Africa",
    "Malta": "Europe",
    "Uruguay": "South America",
    "Georgia": "Asia",
    "Myanmar": "Asia",
    "Kuwait": "Asia",
    "Lào": "Asia",
    "Cyprus": "Europe/Asia",
    "Pakistan": "Asia",
    "Ai Cập": "Africa",
    "Peru": "South America",
    "Iceland": "Europe",
    "Brunei Darussalam": "Asia",
    "Costa Rica": "North America",
    "Nepal": "Asia",
    "Uzbekistan": "Asia",
    "Armenia": "Asia",
    "Turkmenistan": "Asia",
    "Kyrgyzstan": "Asia",
    "Ma Cao": "Asia",
    "Bahrain": "Asia",
    "Algeria": "Africa",
    "Mauritius": "Africa",
    "Tunisia": "Africa",
    "Jersey": "Europe",
    "Azerbaijan": "Asia",
    "Ecuador": "South America",
    "Maldives": "Asia",
    "Kenya": "Africa",
    "Moldova": "Europe",
    "Panama": "North America",
    "Iran": "Asia",
    "Polynesia thuộc Pháp": "Oceania",
    "Montenegro": "Europe",
    "Albania": "Europe",
    "Jordan": "Asia",
    "Andorra": "Europe",
    "Bắc Macedonia": "Europe",
    "Đảo Man": "Europe",
    "Guadeloupe": "North America",
    "Bosnia và Herzegovina": "Europe",
    "Nigeria": "Africa",
    "Venezuela": "South America",
    "Guernsey": "Europe",
    "Guatemala": "North America",
    "Lebanon": "Asia",
    "Martinique": "North America",
    "Bolivia": "South America",
    "Iraq": "Asia",
    "Guiana thuộc Pháp": "South America",
    "Fiji": "Oceania",
    "Gibraltar": "Europe",
    "Các tiểu đảo của Hoa Kỳ": "North America",
    "Liechtenstein": "Europe",
    "Monaco": "Europe",
    "Puerto Rico": "North America",
    "Cộng hòa Dominica": "North America",
    "Tanzania": "Africa",
    "Wallis và Futuna": "Oceania",
    "Uganda": "Africa",
    "Ghana": "Africa",
    "Tajikistan": "Asia",
    "Vanuatu": "Oceania",
    "Zimbabwe": "Africa",
    "Guam": "Oceania",
    "Namibia": "Africa",
    "Butan": "Asia",
    "Yemen": "Asia",
    "Bờ Biển Ngà": "Africa",
    "Trinidad và Tobago": "North America",
    "Jamaica": "North America",
    "Ethiopia": "Africa",
    "Papua New Guinea": "Oceania",
    "Seychelles": "Africa",
    "Paraguay": "South America",
    "Zambia": "Africa",
    "Bonaire St Eustatius và Saba": "North America",
    "Lãnh thổ Palestine": "Asia",
    "Bahamas": "North America",
    "El Salvador": "North America",
    "Quần đảo Virgin thuộc Hoa Kỳ": "North America",
    "Afghanistan": "Asia",
    "Samoa": "Oceania",
    "Madagascar": "Africa",
    "Nicaragua": "North America",
    "Honduras": "North America",
    "Botswana": "Africa",
    "Angola": "Africa",
    "Mozambique": "Africa",
    "Bắc Triều Tiên": "Asia",
    "Cameroon": "Africa",
    "Quần đảo Cayman": "North America",
    "San Marino": "Europe",
    "Đông Timor": "Asia",
    "Curaçao": "North America",
    "Vatican": "Europe",
    "Sudan": "Africa",
    "Anguilla": "North America",
    "Quần đảo Faroe": "Europe",
    "Syria": "Asia",
    "Greenland": "North America",
    "Nam Cực": "Antarctica",
    "Libya": "Africa",
    "Saint Martin": "North America",
    "Eswatini": "Africa",
    "Malawi": "Africa",
    "Barbados": "North America",
    "Belize": "North America",
    "Aruba": "North America",
    "Quần đảo Virgin thuộc Anh": "North America",
    "Senegal": "Africa",
    "Kosovo": "Europe",
    "Bermuda": "North America",
    "Dominica": "North America",
    "Sint Maarten": "North America",
    "Quần đảo Bắc Mariana": "Oceania",
    "Congo": "Africa",
    "Tonga": "Oceania",
    "Rwanda": "Africa",
    "Cuba": "North America",
    "Cộng hòa Gabon": "Africa",
    "Cape Verde": "Africa",
    "Đảo Cook": "Oceania",
    "Antigua & Barbuda": "North America",
    "Suriname": "South America",
    "Togo": "Africa",
    "Somalia": "Africa",
    "Gambia": "Africa",
    "Tuvalu": "Oceania",
    "Djibouti": "Africa",
    "Trung Phi": "Africa",
    "Saint Barthelemy": "North America",
    "Haiti": "North America",
    "Mayotte": "Africa",
    "Liberia": "Africa",
    "Burundi": "Africa",
    "Saint Lucia": "North America",
    "Mali": "Africa",
    "Benin": "Africa",
    "Grenada": "North America",
    "Sierra Leone": "Africa",
    "Quần đảo Svalbard và Jan Mayen": "Europe",
    "Đảo Saint Vincent và Grenadines": "North America",
    "Burkina Faso": "Africa",
    "Mauritania": "Africa",
    "Palau": "Oceania",
    "Chad": "Africa",
    "Quần đảo Turks và Caicos": "North America",
    "Lãnh thổ miền Nam nước Pháp": "Oceania",
    "Tokelau": "Oceania",
    "Đảo Norfolk": "Oceania",
    "Montserrat": "North America",
    "Nauru": "Oceania",
    "Guyana": "South America",
    "Liên bang Saint Kitts và Nevis": "North America",
    "Đảo Bouvet": "Antarctica",
    "Comoros": "Africa",
    "Quần đảo Falkland (Malvinas)": "South America",
    "Niger": "Africa",
    "Quần đảo Solomon": "Oceania",
    "Guinea": "Africa",
    "Quần đảo Cocos (Kneeling)": "Asia/Oceania",
    "Quần đảo Heard và McDonald": "Oceania",
    "Đảo Christmas": "Asia/Oceania",
    "Đảo St. Helena": "Africa",
    "Quần đảo Marshal": "Oceania",
    "Eritrea": "Africa",
    "Micronesia": "Oceania",
    "Lesotho": "Africa",
    "Lãnh thổ Ấn Độ Dương thuộc Anh": "Africa/Oceania",
    "Pitcairn": "Oceania",
    "St. Pierre và Miquelon": "North America",
    "Quần đảo Nam Georgia và Nam Sandwich": "South America",
    "Equitorial Guinea": "Africa",
    "Niue": "Oceania",
    "Kiribati": "Oceania",
    "Guinea-Bissau": "Africa",
}