"""
Gold Layer - Dimension Country Configuration

Source: derived from `silver.hotels_reviews` (column `reviewer_country`)
Target: gold.dim_country (Iceberg table)
"""

# Source table in Silver catalog
SOURCE_TABLE = "hotels_reviews"
SOURCE_COLUMN = "reviewer_country"

# Source catalog/database for Silver. Use fully-qualified name when referencing tables
SOURCE_CATALOG = "silver"
SOURCE_DATABASE = "silver"

# Target table (catalog.database.table)
GOLD_CATALOG = "gold"
GOLD_DATABASE = "gold"
GOLD_TABLE = "dim_country"
GOLD_TABLE_FULL = f"{GOLD_CATALOG}.{GOLD_DATABASE}.{GOLD_TABLE}"

# Business key: country name
BUSINESS_KEY = ["country_name"]

# Optional: manual mapping from country_name -> region (e.g., 'Vietnam': 'Asia')
# Leave empty or add as needed.
COUNTRY_TO_REGION = {
    # Vietnamese country names mapped to regions (English region labels)
    "Afghanistan": "Asia",
    "Albania": "Europe",
    "Algérie": "Africa",
    "Algeria": "Africa",
    "Andorra": "Europe",
    "Angola": "Africa",
    "Antigua và Barbuda": "North America",
    "Antigua and Barbuda": "North America",
    "Argentina": "South America",
    "Armenia": "Asia",
    "Aruba": "North America",
    "Australia": "Oceania",
    "Áo": "Europe",
    "Austria": "Europe",
    "Azerbaijan": "Asia",
    "Azerbaijan": "Asia",
    "Bahamas": "North America",
    "Bahrain": "Asia",
    "Bangladesh": "Asia",
    "Barbados": "North America",
    "Belarus": "Europe",
    "Belgia": "Europe",
    "Bỉ": "Europe",
    "Belgium": "Europe",
    "Belize": "North America",
    "Benin": "Africa",
    "Bhutan": "Asia",
    "Bolivia": "South America",
    "Bosna và Hercegovina": "Europe",
    "Bosnia and Herzegovina": "Europe",
    "Botswana": "Africa",
    "Brazil": "South America",
    "Brunei": "Asia",
    "Bulgaria": "Europe",
    "Burkina Faso": "Africa",
    "Burundi": "Africa",
    "Campuchia": "Asia",
    "Cambodia": "Asia",
    "Cameroon": "Africa",
    "Canada": "North America",
    "Cape Verde": "Africa",
    "Cabo Verde": "Africa",
    "Cộng hòa Trung Phi": "Africa",
    "Central African Republic": "Africa",
    "Chad": "Africa",
    "Chile": "South America",
    "Trung Quốc": "Asia",
    "China": "Asia",
    "Colombia": "South America",
    "Comoros": "Africa",
    "Congo": "Africa",
    "Cộng hòa Dân chủ Congo": "Africa",
    "Congo (Kinshasa)": "Africa",
    "Costa Rica": "North America",
    "Croatia": "Europe",
    "Cuba": "North America",
    "Síp": "Europe",
    "Cyprus": "Europe",
    "Cộng hòa Séc": "Europe",
    "Czechia": "Europe",
    "Czech Republic": "Europe",
    "Bờ Biển Ngà": "Africa",
    "Côte d'Ivoire": "Africa",
    "Đan Mạch": "Europe",
    "Denmark": "Europe",
    "Djibouti": "Africa",
    "Dominica": "North America",
    "Cộng hòa Dominica": "North America",
    "Dominican Republic": "North America",
    "Ecuador": "South America",
    "Ai Cập": "Africa",
    "Egypt": "Africa",
    "El Salvador": "North America",
    "Equatorial Guinea": "Africa",
    "Guinea Xích Đạo": "Africa",
    "Eritrea": "Africa",
    "Estonia": "Europe",
    "Eswatini": "Africa",
    "Ethiopia": "Africa",
    "Fiji": "Oceania",
    "Phần Lan": "Europe",
    "Finland": "Europe",
    "Pháp": "Europe",
    "France": "Europe",
    "Gabon": "Africa",
    "Gambia": "Africa",
    "Georgia": "Asia",
    "Gruzia": "Asia",
    "Đức": "Europe",
    "Germany": "Europe",
    "Ghana": "Africa",
    "Hy Lạp": "Europe",
    "Greece": "Europe",
    "Grenada": "North America",
    "Guatemala": "North America",
    "Guinea": "Africa",
    "Guinea-Bissau": "Africa",
    "Guyana": "South America",
    "Haiti": "North America",
    "Honduras": "North America",
    "Hungary": "Europe",
    "Hungary": "Europe",
    "Iceland": "Europe",
    "Ấn Độ": "Asia",
    "India": "Asia",
    "Indonesia": "Asia",
    "Iran": "Asia",
    "Iraq": "Asia",
    "Ireland": "Europe",
    "Ireland": "Europe",
    "Israel": "Asia",
    "Ý": "Europe",
    "Italy": "Europe",
    "Jamaica": "North America",
    "Japan": "Asia",
    "Nhật Bản": "Asia",
    "Jordan": "Asia",
    "Kazakhstan": "Asia",
    "Kenya": "Africa",
    "Kiribati": "Oceania",
    "Kosovo": "Europe",
    "Kuwait": "Asia",
    "Kyrgyzstan": "Asia",
    "Lào": "Asia",
    "Laos": "Asia",
    "Latvia": "Europe",
    "Lebanon": "Asia",
    "Liechtenstein": "Europe",
    "Lithuania": "Europe",
    "Luxembourg": "Europe",
    "Madagascar": "Africa",
    "Malawi": "Africa",
    "Malaysia": "Asia",
    "Maldives": "Asia",
    "Mali": "Africa",
    "Malta": "Europe",
    "Marshall Islands": "Oceania",
    "Mauritania": "Africa",
    "Mauritius": "Africa",
    "Mexico": "North America",
    "Micronesia": "Oceania",
    "Moldova": "Europe",
    "Monaco": "Europe",
    "Mongolia": "Asia",
    "Montenegro": "Europe",
    "Morocco": "Africa",
    "Mozambique": "Africa",
    "Myanmar": "Asia",
    "Burma": "Asia",
    "Namibia": "Africa",
    "Nauru": "Oceania",
    "Nepal": "Asia",
    "Hà Lan": "Europe",
    "Netherlands": "Europe",
    "New Zealand": "Oceania",
    "Nicaragua": "North America",
    "Niger": "Africa",
    "Nigeria": "Africa",
    "Bắc Triều Tiên": "Asia",
    "North Korea": "Asia",
    "Bắc Macedonia": "Europe",
    "North Macedonia": "Europe",
    "Na Uy": "Europe",
    "Norway": "Europe",
    "Oman": "Asia",
    "Pakistan": "Asia",
    "Palau": "Oceania",
    "Panama": "North America",
    "Papua New Guinea": "Oceania",
    "Paraguay": "South America",
    "Peru": "South America",
    "Philippines": "Asia",
    "Philippines": "Asia",
    "Ba Lan": "Europe",
    "Poland": "Europe",
    "Bồ Đào Nha": "Europe",
    "Portugal": "Europe",
    "Qatar": "Asia",
    "Romania": "Europe",
    "Nga": "Europe/Asia",
    "Russia": "Europe/Asia",
    "Rwanda": "Africa",
    "Saint Kitts và Nevis": "North America",
    "Saint Lucia": "North America",
    "Saint Vincent và Grenadines": "North America",
    "Samoa": "Oceania",
    "San Marino": "Europe",
    "Sao Tome và Principe": "Africa",
    "Saudi Arabia": "Asia",
    "Ả Rập Xê Út": "Asia",
    "Senegal": "Africa",
    "Serbia": "Europe",
    "Seychelles": "Africa",
    "Sierra Leone": "Africa",
    "Singapore": "Asia",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Quần đảo Solomon": "Oceania",
    "Solomon Islands": "Oceania",
    "Somalia": "Africa",
    "Nam Phi": "Africa",
    "South Africa": "Africa",
    "Hàn Quốc": "Asia",
    "South Korea": "Asia",
    "Nam Sudan": "Africa",
    "South Sudan": "Africa",
    "Tây Ban Nha": "Europe",
    "Spain": "Europe",
    "Sri Lanka": "Asia",
    "Sudan": "Africa",
    "Suriname": "South America",
    "Thụy Điển": "Europe",
    "Sweden": "Europe",
    "Thụy Sĩ": "Europe",
    "Switzerland": "Europe",
    "Syria": "Asia",
    "Đài Loan": "Asia",
    "Taiwan": "Asia",
    "Tajikistan": "Asia",
    "Tanzania": "Africa",
    "Thái Lan": "Asia",
    "Thailand": "Asia",
    "Đông Timor": "Asia",
    "Timor-Leste": "Asia",
    "Togo": "Africa",
    "Tonga": "Oceania",
    "Trinidad và Tobago": "North America",
    "Tunisia": "Africa",
    "Thổ Nhĩ Kỳ": "Europe/Asia",
    "Turkey": "Europe/Asia",
    "Turkmenistan": "Asia",
    "Tuvalu": "Oceania",
    "Uganda": "Africa",
    "Ukraine": "Europe",
    "United Arab Emirates": "Asia",
    "Các Tiểu vương quốc Ả Rập Thống nhất": "Asia",
    "Vương quốc Anh": "Europe",
    "United Kingdom": "Europe",
    "Hoa Kỳ": "North America",
    "Mỹ": "North America",
    "United States": "North America",
    "Uruguay": "South America",
    "Uzbekistan": "Asia",
    "Vanuatu": "Oceania",
    "Vatican": "Europe",
    "Venezuela": "South America",
    "Việt Nam": "Asia",
    "Yemen": "Asia",
    "Zambia": "Africa",
    "Zimbabwe": "Africa",
}
